# -*- coding: utf-8 -*-
"""Hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXz7m2-TNzCY9Vvfhs5RJNJRO_-vyiSh
"""

print('Hello')