# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y04GKyaRdcIUqV9oPGYEsb4wxkjjVlrW
"""

def hello(name):
  print('Hello ' + name + '!')
  return

def hello2(name):
  print('Hello2 ' + name + '!')
  return
